#' @export

# Basic theme by PG

theme_PG <- function (base_size = 7, base_col = "gray30", base_family = "", base_face = "plain") {
  half_line <- base_size/2
  theme(line = element_line(colour = base_col, size = 0.5, linetype = 1,
                            lineend = "butt"), 
        rect = element_rect(fill = "white", colour = base_col, size = 0.5, linetype = 1),
        text = element_text(family = base_family, face = base_face, 
                            colour = base_col, size = base_size, lineheight = 0.9, 
                            hjust = 0.5, vjust = 0.5, angle = 0, 
                            margin = ggplot2::margin(), debug = FALSE), 
        axis.line = element_line(colour = base_col), 
        axis.text = element_text(size = base_size, colour = base_col, face = base_face), 
        axis.text.x = element_text(margin = ggplot2::margin(t = 1.2 * half_line/2), vjust = 1), 
        axis.text.y = element_text(margin = ggplot2::margin(r = 1.2 * half_line/2), hjust = 1),
        axis.ticks = element_line(colour = base_col),
        axis.ticks.length = unit(half_line/1.5, "pt"), 
        axis.title.x = element_text(margin = ggplot2::margin(t = 1.4 * half_line, b = 0.8 * half_line/2)),
        axis.title.y = element_text(angle = 90, margin = ggplot2::margin(r = 1.5 * half_line, l = 0.8 * half_line/2)),
        legend.background = element_rect(colour = NA), 
        legend.spacing = unit(0.2, "cm"), 
        legend.key = element_rect(fill = NULL, colour = "white"),
        legend.key.size = unit(1.2, "lines"),
        legend.key.height = NULL, 
        legend.key.width = NULL, 
        legend.text = element_text(size = base_size),
        legend.text.align = NULL, 
        legend.title = element_text(hjust = 0),
        legend.title.align = NULL, 
        legend.position = "right",
        legend.direction = NULL,
        legend.justification = "center",
        legend.box = NULL,
        panel.background = element_blank(),
        panel.border = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.spacing = unit(half_line, "pt"), 
        panel.spacing.x = NULL,
        panel.spacing.y = NULL,
        panel.ontop = FALSE,
        strip.background = element_rect(fill = "grey85", colour = NA),
        strip.text = element_text(colour = "grey10", size = base_size), 
        strip.text.x = element_text(margin = ggplot2::margin(t = half_line, b = half_line)),
        strip.text.y = element_text(angle = -90, margin = ggplot2::margin(l = half_line, r = half_line)), 
        strip.switch.pad.grid = unit(0.1, "cm"),
        strip.switch.pad.wrap = unit(0.1, "cm"),
        plot.background = element_rect(colour = "white"),
        plot.title = element_text(size = base_size+1, hjust = 0, face = "bold",
                                  margin = ggplot2::margin(b = half_line *1.2)),
        plot.margin = ggplot2::margin(half_line, half_line, half_line, half_line),
        complete = TRUE)
}
